server:
  port: 8812

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
rabbitmq:
  receive:
    queues:
      messages: MSG_Q